train: /home/GPU/tsutar/home_gtl/intro_to_res/pose_detection_dataset/train/images # Path to training images
val: /home/GPU/tsutar/home_gtl/intro_to_res/pose_detection_dataset/val/images # Path to validation images
test: /home/GPU/tsutar/home_gtl/intro_to_res/pose_detection_dataset/test/images # Path to test images (optional)

nc: 3 # Number of classes
names:

- player_blue
- player_white
- referee
